export const EMAIL_OR_PASSWORD_NOT_RIGHT = 'EMAIL_OR_PASSWORD_NOT_RIGHT';

export const EMAIL_NOT_EXIST = 'EMAIL_NOT_EXIST';

export const PASSWORD_DIFFERENT_REPEAT_PASSWORD =
  'PASSWORD_DIFFERENT_REPEAT_PASSWORD';

export const USER_NOT_EXIST = 'USER_NOT_EXIST';

export const EMAIL_EXISTED = 'EMAIL_EXISTED';

export const AUTHORIZATION_HEADER_REQUIRED = 'AUTHORIZATION_HEADER_REQUIRED';
